### PR TITLE
feat(loader): .gpkg loader 

### PR DESCRIPTION
**Pull request by jfb-h**
Reopen #14, this time with tests!

### CODE REVIEW

**Comment by tecosaur** [comment]
Love it, thanks for adding tests too :heart_eyes:

**Comment by tecosaur** [comment]
You don't need to `using ArchGDAL` in `runtests.jl`, it will be automatically loaded as normal.

**Comment by tecosaur** [comment]
I can take care of that though if I merge this locally (might make this PR show up as "closed" though, but that's just cosmetics at the end of the day, the commit log will still show this contribution as coming from you).

**Comment by jfb-h** [comment]
> You don't need to `using ArchGDAL` in `runtests.jl`, it will be automatically loaded as normal.

I thought so, but when I don't explicitly load it, the test fails with a `TransformerError: Data set "eurostat-gpkg" could not be loaded in any form.`. Did I miss something?

**Comment by tecosaur** [comment]
:thinking: I'll have a look locally

**Comment by jfb-h** [comment]
Hi @tecosaur, I know you have a lot on your hands, but is there any chance this could be merged soonish? I have a project where I'd love to transition to `DataToolkit.jl` but which requires handling `.gpkg` files. Thanks a lot for all your effort!

**Comment by tecosaur** [comment]
Sorry for the delay (I'm beginning to get a bit busier, feel free to ping me like this though :slightly_smiling_face:), and thanks for the contribution.

I'll give this a second look now.

**Comment by tecosaur** [comment]
I've just made a few tweaks, and realised the what the problem was/reason why `ArchGDAL` had to be loaded explicitly. It's because the `ArchGDAL` type specified in `supportedtypes` doesn't exist before the package is loaded, and so `DataToolkitBase` can't infer anything about the type. I've thought of an only slightly kludgy fix, I'll push that and merge this in a sec.

**Comment by tecosaur** [comment]
The failing CI check now seems to be

```
gpkg: Test Failed at /home/tec/.julia/dev/DataToolkitCommon/test/runtests.jl:28
  Expression: ArchGDAL.getlayer(geo, 0) |> length == 16
   Evaluated: 1025 == 16
```

let me know if this represents an actual issue, or if this should just be ` ... == 1025`.

**Comment by jfb-h** [comment]
Ah damn, I swear I tested that locally... Yeah it should indeed be 1025, I must have mixed up the files. Thanks a lot for looking into this!

**Pull request merged**
